#SPDX-License-Identifier: MIT
os: linux
dist: xenial
language: python
services:
  - docker

jobs:
  include:
    - name: Python v3.6 Unit Tests
      python: 3.6
      env: TOXENV=py36-workers,py36-application

    - name: Python v3.6 API Tests
      python: 3.6
      env: TOXENV=py36-metric-routes

    - name: Python v3.7 Unit Tests
      python: 3.7
      env: TOXENV=py37-workers,py37-application

    - name: Python v3.7 API Tests
      python: 3.7
      env: TOXENV=py37-metric-routes

    - name: Python v3.8 Unit Tests
      python: 3.8
      env: TOXENV=py38-workers,py38-application

    - name: Python v3.8 API Tests
      python: 3.8
      env: TOXENV=py38-metric-routes

env:
  global:
    AUGUR_DB_HOST=localhost
    AUGUR_DB_NAME=test_data
    AUGUR_DB_PORT=5432
    AUGUR_DB_USER=augur
    AUGUR_DB_PASSWORD=augur

before_install:
  - docker run -d -p 5432:5432 --name augur_test_database augurlabs/augur:test_data@sha256:71da12114bf28584a9a64ede2fac0cbc8dffc8e2f4a2c61231206e2f82201c2f
install:
  - ./scripts/install/backend.sh
  - ./scripts/install/workers.sh
  - augur config init

script:
  - tox
