database:
  - schema/*
  - schema/**/*

backend:
  - augur/*
  - augur/**/*

frontend:
  - frontend/src/*
  - frontend/src/**/*

installation:
  - scripts/install/*
  - scripts/install/**/*

CLI:
  - augur/cli/*
  - augur/cli/**/*

metric:
  - augur/metrics/*
  - augur/metrics/**/*

testing:
  - test/*
  - test/**/*
  - tox.ini

workers:
  - workers/*
  - workers/**/*

docker:
  - util/docker/*
  - util/docker/**/*
  - .dockerignore

documentation:
  - docs/source/*
  - docs/source/**/*