# SPDX-License-Identifier: MIT
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      packages:
        - sphinx
        - sphinx_rtd_theme

sphinx:
  configuration: docs/source/conf.py

formats: all
