#SPDX-License-Identifier: MIT
version: '3'
services:
   database:
    image: augurlabs/augur:${AUGUR_DB_TYPE}
    build:
      context: .
      dockerfile: ./util/docker/database/Dockerfile
    restart: unless-stopped
    ports:
     - 5434:5432
