#SPDX-License-Identifier: MIT
#Format for ports: <outside>:<inside>
version: '3'
services:
   database:
    image: augurlabs/augur:${AUGUR_DB_TYPE}
    restart: unless-stopped
    ports:
     - 5434:5432