version: '3'
services:
     augur:
       build:
        dockerfile: util/packaging/docker/augur/Dockerfile
       image: augurlabs/augur:latest
       restart: always
       ports:
         - 5000:5000
       env_file: env.txt

      frontend:
        build:
          dockerfile: util/packaging/docker/frontend/Dockerfile
        image: node:10
        restart: always
        ports:
            - 8080:8080


