#SPDX-License-Identifier: MIT
version: '3'
services:
  database:
    image: augurlabs/augur:database
    build:
      context: .
      dockerfile: ./docker/database/Dockerfile
    restart: unless-stopped
    ports:
      - "${AUGUR_DB_PORT:-5432}:5432"
    volumes:
      - augur:/var/lib/postgresql/data

  backend:
    image: augurlabs/augur:backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    # volumes:
    #   - ./path/to/your/repo_groups.csv:/repo_groups.csv
    #   - ./path/to/your/repos.csv:/repos.csv
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - "AUGUR_DB_SCHEMA_BUILD=0"
      - "AUGUR_DB_HOST=database"
      - "AUGUR_DB_NAME=augur"
      - "AUGUR_DB_PASSWORD=augur"
      - "AUGUR_DB_PORT=${AUGUR_DB_PORT:-5432}"
    depends_on:
      - database

  frontend:
    image: augurlabs/augur:frontend
    build:
      context: .
      dockerfile: ./docker/frontend/prod.dockerfile
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - backend

volumes:
  augur:
