from augur.tasks.data_analysis.clustering_worker import clustering_model
from augur.tasks.data_analysis.contributor_breadth_worker import contributor_breadth_model
from augur.tasks.data_analysis.discourse_analysis import discourse_analysis_model
from augur.tasks.data_analysis.insight_worker import insights_model
from augur.tasks.data_analysis.message_insights import message_insights_model
from augur.tasks.data_analysis.pull_request_analysis_worker import pull_request_analysis_model
