from augur.tasks.data_analysis.tasks.clustering_worker import clustering_model
from augur.tasks.data_analysis.tasks.contributor_breadth_worker import contributor_breadth_model
from augur.tasks.data_analysis.tasks.discourse_analysis import discourse_analysis_model
from augur.tasks.data_analysis.tasks.insight_worker import insights_model
from augur.tasks.data_analysis.tasks.message_insights import message_insights_model
from augur.tasks.data_analysis.tasks.pull_request_analysis_worker import pull_request_analysis_model
