"""Create basic tables

Revision ID: 2eaa930b1f5a
Revises: 
Create Date: 2019-02-09 16:10:24.251828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eaa930b1f5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo',
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('vcs', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('url')
    )
    op.create_table('repo_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email_confirmation_token', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('password_updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('authenticated', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('repo_group_has_project',
    sa.Column('repo_group_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['repo_group_id'], ['repo_group.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repo.url'], ),
    sa.PrimaryKeyConstraint('repo_group_id', 'repo_id')
    )
    op.create_table('user_has_repo_group',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repo_group_id'], ['repo_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'repo_group_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_has_repo_group')
    op.drop_table('repo_group_has_project')
    op.drop_table('user')
    op.drop_table('repo_group')
    op.drop_table('repo')
    # ### end Alembic commands ###
