#!/bin/bash

host=$1
database=$2
db_user=$3
port=$4

psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.analysis_log from  'schema/data/analysis_log.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.repo_groups from  'schema/data/repo_groups.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.repo from  'schema/data/repo.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.contributors from  'schema/data/contributors.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.issues from  'schema/data/issues.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.pull_requests from  'schema/data/pull_requests.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.message from  'schema/data/message.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.commit_parents from  'schema/data/commit_parents.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.contributors_aliases from  'schema/data/contributors_aliases.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.contributor_affiliations from  'schema/data/contributor_affiliations.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.contributors_history from  'schema/data/contributors_history.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.dm_repo_annual from  'schema/data/dm_repo_annual.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.commits from  'schema/data/commits.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.dm_repo_group_annual from  'schema/data/dm_repo_group_annual.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.dm_repo_group_monthly from  'schema/data/dm_repo_group_monthly.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.dm_repo_group_weekly from  'schema/data/dm_repo_group_weekly.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.dm_repo_monthly from  'schema/data/dm_repo_monthly.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.dm_repo_weekly from  'schema/data/dm_repo_weekly.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.exclude from  'schema/data/exclude.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.issue_labels from  'schema/data/issue_labels.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.issue_message_ref from  'schema/data/issue_message_ref.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.issue_events from  'schema/data/issue_events.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.issue_assignees from  'schema/data/issue_assignees.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.libraries from  'schema/data/libraries.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.library_dependencies from  'schema/data/library_dependencies.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.library_version from  'schema/data/library_version.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.pull_request_assignees from  'schema/data/pull_request_assignees.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.pull_request_events from  'schema/data/pull_request_events.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.pull_request_labels from  'schema/data/pull_request_labels.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.pull_request_message_ref from  'schema/data/pull_request_message_ref.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.pull_request_meta from  'schema/data/pull_request_meta.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.pull_request_teams from  'schema/data/pull_request_teams.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.pull_request_repo from  'schema/data/pull_request_repo.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.repo_groups_list_serve from  'schema/data/repo_groups_list_serve.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.repo_group_insights from  'schema/data/repo_group_insights.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.repo_ghtorrent_map from  'schema/data/repo_ghtorrent_map.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.repo_info from  'schema/data/repo_info.txt'" 
# psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.repo_badging from  'schema/data/repo_badging.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.repo_insights from  'schema/data/repo_insights.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.repo_insights_records from  'schema/data/repo_insights_records.txt'" 
# psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.repo_labor from  'schema/data/repo_labor.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.repo_meta from  'schema/data/repo_meta.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.pull_request_reviewers from  'schema/data/pull_request_reviewers.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.repo_test_coverage from  'schema/data/repo_test_coverage.txt'" 
psql -h $host -d $database -U $db_user -p $port -a -w -c "\copy augur_data.repos_fetch_log from  'schema/data/repos_fetch_log.txt'" 
