"""No null author affiliation and committer affiliation in commits table

Revision ID: 7
Revises: 6
Create Date: 2023-02-23 10:14:08.787528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text
import re


# revision identifiers, used by Alembic.
revision = '13'
down_revision = '12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(text(f"""
          ALTER TABLE "augur_data"."commits" 
          ALTER COLUMN "cmt_author_affiliation" SET DEFAULT NULL,
          ALTER COLUMN "cmt_committer_affiliation" SET DEFAULT NULL;
        """))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
