"""No null repo_path and repo_name

Revision ID: 7
Revises: 6
Create Date: 2023-02-23 10:14:08.787528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text
import re


# revision identifiers, used by Alembic.
revision = '13'
down_revision = '12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    result = conn.execute(text("""SELECT * FROM repo WHERE repo_path IS NULL or repo_name IS NULL;""")).fetchall()
    if result:

        for row in result:
            regex = re.search(r"https:\/\/(github\.com\/[A-Za-z0-9 \- _]+\/)([A-Za-z0-9 \- _ .]+)$", row.repo_git)
            if not regex:
                continue
            
            repo_path = regex[0]
            repo_name = regex[1]
            conn.execute(text(f"""
                  ALTER TABLE "augur_data"."commits" 
                  ALTER COLUMN "cmt_author_affiliation" SET DEFAULT NULL,
                  ALTER COLUMN "cmt_committer_affiliation" SET DEFAULT NULL;
                """).bindparams(path=repo_path,name=repo_name,repo_git=row.repo_git))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
