"""Frequent vaccuming on high update commits table

Revision ID: 14
Revises: 13
Create Date: 2023-02-23 10:14:08.787528

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text
import re


# revision identifiers, used by Alembic.
revision = '14'
down_revision = '13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(text(f"""
        ALTER TABLE augur_data.commits SET (autovacuum_vacuum_scale_factor = 0, autovacuum_vacuum_threshold = 1000);
        """))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
