"""Schedule any old facade repositories to be re-cloned

Revision ID: 18
Revises: 17
Create Date: 2023-05-02 17:35:18.891913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text
import pathlib
import shutil
from augur.application.config import AugurConfig
from augur.application.db.session import DatabaseSession
import logging

# revision identifiers, used by Alembic.
revision = '18'
down_revision = '17'
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)


def total_facade_reset():
    conn = op.get_bind()

    conn.execute(text(f"""

    UPDATE augur_operations.collection_status
    SET facade_status='Pending', facade_task_id=NULL, facade_weight=NULL,commit_sum=NULL;

    UPDATE augur_data.repos
    SET repo_path=NULL,repo_name=NULL;
    """))

    

    try:
        with DatabaseSession(logger) as session:
            config = AugurConfig(logger, session).get_section("Facade")
            facade_base_dir = config['repo_directory']
        
        path = pathlib.Path(facade_base_dir)
        shutil.rmtree(path)
    except:
        pass

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
    total_facade_reset()



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    total_facade_reset()
