"""Schedule any old facade repositories to be re-cloned

Revision ID: 18
Revises: 17
Create Date: 2023-05-02 17:35:18.891913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '18'
down_revision = '17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
    conn = op.get_bind()



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
