"""change type of cmt_ght_author_id

Revision ID: 9
Revises: 8
Create Date: 2022-07-29 11:19:21.471543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9'
down_revision = '8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commits', 'cmt_ght_author_id',
               existing_type=sa.INTEGER(),
               type_=postgresql.UUID(as_uuid=True),
               existing_nullable=True,
               schema='augur_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('commits', 'cmt_ght_author_id',
               existing_type=postgresql.UUID(as_uuid=True),
               type_=sa.INTEGER(),
               existing_nullable=True,
               schema='augur_data')
    # ### end Alembic commands ###
