"""Add admin column to User table

Revision ID: 10
Revises: 9
Create Date: 2022-08-05 13:03:40.458304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10'
down_revision = '9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=False), schema='augur_operations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin', schema='augur_operations')
    # ### end Alembic commands ###
