"""Add user repo table

Revision ID: 12
Revises: 11
Create Date: 2022-09-28 11:25:36.010611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12'
down_revision = '11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_repos',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['augur_data.repo.repo_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['augur_operations.users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'repo_id'),
    schema='augur_operations'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_repos', schema='augur_operations')
    # ### end Alembic commands ###
