"""Add user repo table

Revision ID: 12
Revises: 11
Create Date: 2022-09-28 11:25:36.010611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text



# revision identifiers, used by Alembic.
revision = '12'
down_revision = '11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_repos',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['augur_data.repo.repo_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['augur_operations.users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'repo_id'),
    schema='augur_operations'
    )

    conn = op.get_bind()
    conn.execute(text("""INSERT INTO "augur_operations"."users" ("user_id", "login_name", "login_hashword", "email", "text_phone", "first_name", "last_name", "tool_source", "tool_version", "data_source", "data_collection_date", "admin") VALUES(1, 'cli_user', 'pbkdf2:sha256:260000$oDmAfipU8Ef8TAau$835fce1fc3290b57b5e02ec83aef4613cc06664e6e7535bb6d267dc44563d5d5', 'cli_user', NULL, 'cli_user', 'cli_user', 'Schema Generaation', NULL, 'Schema Generation', '2022-10-02 21:49:13', 'f')"""))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_repos', schema='augur_operations')

    conn = op.get_bind()
    conn.execute(text("""DELETE FROM "augur_operations"."users" WHERE user_id=1"""))
    # ### end Alembic commands ###
