"""Add config table

Revision ID: 3
Revises: 2
Create Date: 2022-07-12 11:00:35.548626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3'
down_revision = '2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=False),
    sa.Column('setting_name', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_name', 'setting_name', name='unique-config-setting'),
    schema='augur_operations'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config', schema='augur_operations')
    # ### end Alembic commands ###
