"""change type of cmt_ght_author_id

Revision ID: 9
Revises: 8
Create Date: 2022-07-29 12:04:20.064429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '9'
down_revision = '8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('commits', 'cmt_ght_author_id',
    #           existing_type=sa.INTEGER(),
    #           type_=postgresql.UUID(as_uuid=True),
    #           existing_nullable=True,
    #           schema='augur_data')
    # ### end Alembic commands ###

    conn = op.get_bind()
    conn.execute(text("""DELETE FROM commits"""))
    op.drop_column('commits', 'cmt_ght_author_id')

    op.add_column('commits', sa.Column('cmt_ght_author_id', postgresql.UUID(as_uuid=True), nullable=True), schema='augur_data')
    op.create_index('author_cntrb_id', 'commits', ['cmt_ght_author_id'], unique=False, schema='augur_data')
    op.create_foreign_key(None, 'commits', 'contributors', ['cmt_ght_author_id'], ['cntrb_id'], source_schema='augur_data', referent_schema='augur_data')
    

    


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.alter_column('commits', 'cmt_ght_author_id',
    #           existing_type=postgresql.UUID(as_uuid=True),
    #           type_=sa.INTEGER(),
    #           existing_nullable=True,
    #           schema='augur_data')
    # ### end Alembic commands ###

    conn = op.get_bind()
    conn.execute(text("""DELETE FROM commits"""))

    op.drop_column('commits', 'cmt_ght_author_id')
    op.add_column('commits', sa.Column('cmt_ght_author_id', sa.INTEGER, nullable=True), schema='augur_data') 
    op.create_index('author_cntrb_id', 'commits', ['cmt_ght_author_id'], unique=False, schema='augur_data')