"""Added user group table

Revision ID: 2
Revises: 1
Create Date: 2022-12-19 11:00:37.509132

"""
import logging

from alembic import op
import sqlalchemy as sa
from augur.application.db.session import DatabaseSession
from augur.application.db.models.augur_operations import UserGroup, UserRepo



# revision identifiers, used by Alembic.
revision = '2'
down_revision = '1'
branch_labels = None
depends_on = None

logger = logging.getLogger(__name__)

def upgrade():

    with DatabaseSession(logger) as session:

        print("Creating user groups table")
        create_user_groups_table = """    
            CREATE TABLE "augur_operations"."user_groups" (
                "group_id" BIGSERIAL NOT NULL,
                "user_id" int4 NOT NULL,
                "name" varchar COLLATE "pg_catalog"."default" NOT NULL,
                PRIMARY KEY ("group_id"),
                FOREIGN KEY ("user_id") REFERENCES "augur_operations"."users" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION,
                UNIQUE ("user_id", "name")
            );


                ALTER TABLE "augur_operations"."user_groups" 
                OWNER TO "augur";
            """

        session.execute_sql(sa.sql.text(create_user_groups_table))


        user_repos = []

        print("Creating user groups")
        # create user group for all the users that have repos
        user_id_query = sa.sql.text("""SELECT DISTINCT(user_id) FROM user_repos;""")
        user_groups = session.fetchall_data_from_sql_text(user_id_query)
        if user_groups:

            result = []
            for row in user_groups:
                
                user_id = row["user_id"]

                user_group_insert = sa.sql.text(f"""INSERT INTO "augur_operations"."user_groups" ("user_id", "name") VALUES ({user_id}, 'default') RETURNING group_id, user_id;""")
                result.append(session.fetchall_data_from_sql_text(user_group_insert)[0])
            
            user_group_id_mapping = {}
            for row in result:
                user_group_id_mapping[row["user_id"]] = row["group_id"]
            

            print("Getting users repos")
            user_repo_query = sa.sql.text("""SELECT * FROM user_repos;""")
            user_repo_data = session.fetchall_data_from_sql_text(user_repo_query)
            for row in user_repo_data:
                row.update({"group_id": user_group_id_mapping[row["user_id"]]})
                del row["user_id"]
            user_repos.extend(user_repo_data)

            print("Removing data from user repos table")
            # remove data from table before modifiying it
            remove_data_from_user_repos_query = sa.sql.text("""DELETE FROM user_repos;""")
            session.execute_sql(remove_data_from_user_repos_query)


        table_changes = """
        ALTER TABLE user_repos
            ADD COLUMN group_id INT,
            ADD CONSTRAINT user_repos_group_id_fkey FOREIGN KEY (group_id) REFERENCES user_groups(group_id),
            DROP COLUMN user_id,
            ADD PRIMARY KEY (group_id, repo_id);
        """

        session.execute_sql(sa.sql.text(table_changes))

        print(user_repos)

        print("Inserting data into user repos table")
        for data in user_repos:

            group_id = data["group_id"]
            repo_id = data["repo_id"]

            user_repo_insert = sa.sql.text(f"""INSERT INTO "augur_operations"."user_repos" ("group_id", "repo_id") VALUES ({group_id}, {repo_id});""")
            result = session.execute_sql(user_repo_insert)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    print("Downgrade")

    user_group_ids = {}
    group_repo_ids = {}
    with DatabaseSession(logger) as session:
        user_id_query = sa.sql.text("""SELECT * FROM user_groups;""")
        user_groups = session.fetchall_data_from_sql_text(user_id_query)
        for row in user_groups:
            try:
                user_group_ids[row["user_id"]].append(row["group_id"])
            except KeyError:
                user_group_ids[row["user_id"]] = [row["group_id"]]


        group_id_query = sa.sql.text("""SELECT * FROM user_repos;""")
        group_repo_id_result = session.fetchall_data_from_sql_text(group_id_query)
        for row in group_repo_id_result:
            try:
                group_repo_ids[row["group_id"]].append(row["repo_id"])
            except KeyError:
                group_repo_ids[row["group_id"]] = [row["repo_id"]]

        remove_data_from_user_repos_query = sa.sql.text("""DELETE FROM user_repos;""")
        session.execute_sql(remove_data_from_user_repos_query)


        table_changes = """
        ALTER TABLE user_repos
            ADD COLUMN user_id INT,
            ADD CONSTRAINT user_repos_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(user_id),
            DROP COLUMN group_id,
            ADD PRIMARY KEY (user_id, repo_id);
        DROP TABLE user_groups;
        """

        session.execute_sql(sa.sql.text(table_changes))


        print("user group ids")
        print(user_group_ids)

        print("Group repo ids")
        print(group_repo_ids)

        for user_id, group_ids in user_group_ids.items():

            print(f"User id: {user_id}")
            print(f"Group ids: {group_ids}")

            repos = []
            for group_id in group_ids:
                try:
                    repos.extend(group_repo_ids[group_id])
                except KeyError:
                    continue

            print(f"User: {user_id} Repos: {repos}")

            query_text_array = ["""INSERT INTO "augur_operations"."user_repos" ("repo_id", "user_id") VALUES """]
            for i, repo_id in enumerate(repos):
                query_text_array.append(f"({repo_id}, {user_id})")

                delimiter = ";" if i == len(repos) -1 else ","

                query_text_array.append(delimiter)


            query_text = "".join(query_text_array)

            print(query_text)

            session.execute_sql(sa.sql.text(query_text))

    # ### end Alembic commands ###
