"""change config table to add toggle to force facade to recollect through all commits

Revision ID: 34
Revises: 33
Create Date: 2025-10-02 12:45:57.486871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '34'
down_revision = '33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #Add toggle for facade collection.
    conn = op.get_bind()

    conn.execute(text(f"""
        INSERT INTO "augur_operations"."config" ("section_name", "setting_name", "value", "type") VALUES ('Facade', 'facade_contributor_full_recollect', '{0}', 'int');
        """))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute(text(f"""
        DELETE FROM "augur_operations"."config" WHERE section_name = 'Facade' AND setting_name = 'facade_contributor_full_recollect' AND type = 'int';
        """))
    # ### end Alembic commands ###
