"""sync topic model migrations because Revisions 35 and 36 did not perfectly match their associated SQLAlchemy class models.

Revision ID: 37
Revises: 36
Create Date: 2025-11-14 17:09:14.156057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37'
down_revision = '36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic_model_event', 'event_id',
               existing_type=sa.BIGINT(),
               comment='Unique identifier for the event',
               existing_nullable=False,
               autoincrement=True,
               schema='augur_data')
    op.alter_column('topic_model_event', 'ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Timestamp when the event occurred',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='augur_data')
    op.alter_column('topic_model_event', 'repo_id',
               existing_type=sa.INTEGER(),
               comment='Repository associated with this event',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('topic_model_event', 'model_id',
               existing_type=sa.UUID(),
               comment='Topic model associated with this event',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('topic_model_event', 'event',
               existing_type=sa.TEXT(),
               comment='Event type or name',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_event', 'level',
               existing_type=sa.TEXT(),
               comment='Log level (INFO, WARNING, ERROR, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'INFO'::text"),
               schema='augur_data')
    op.alter_column('topic_model_event', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Event payload data',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'model_id',
               existing_type=sa.UUID(),
               comment='Unique identifier for the topic model',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'),
               schema='augur_data')
    op.alter_column('topic_model_meta', 'repo_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               comment='Repository this model was trained on',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'model_method',
               existing_type=sa.VARCHAR(),
               comment="Method used for topic modeling (e.g., 'NMF_COUNT', 'LDA_TFIDF')",
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'num_topics',
               existing_type=sa.INTEGER(),
               comment='Number of topics in the model',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'num_words_per_topic',
               existing_type=sa.INTEGER(),
               comment='Number of words per topic',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'training_parameters',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='JSON object containing training parameters',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'model_file_paths',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='JSON object containing paths to model artifacts',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'parameters_hash',
               existing_type=sa.VARCHAR(),
               comment='Hash of parameters for deduplication',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'coherence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Coherence score of the model',
               existing_nullable=False,
               existing_server_default=sa.text('0.0'),
               schema='augur_data')
    op.alter_column('topic_model_meta', 'perplexity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Perplexity score of the model',
               existing_nullable=False,
               existing_server_default=sa.text('0.0'),
               schema='augur_data')
    op.alter_column('topic_model_meta', 'topic_diversity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Topic diversity score',
               existing_nullable=False,
               existing_server_default=sa.text('0.0'),
               schema='augur_data')
    op.alter_column('topic_model_meta', 'quality',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='Quality metrics',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"),
               schema='augur_data')
    op.alter_column('topic_model_meta', 'training_message_count',
               existing_type=sa.BIGINT(),
               comment='Number of messages used for training',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'data_fingerprint',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='Fingerprint of training data',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'visualization_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               comment='JSON object containing visualization data for the model',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'training_start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When training started',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'training_end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When training ended',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'tool_source',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='Standard Augur Metadata',
               schema='augur_data')
    op.alter_column('topic_model_meta', 'tool_version',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='Standard Augur Metadata',
               schema='augur_data')
    op.alter_column('topic_model_meta', 'data_source',
               existing_type=sa.VARCHAR(),
               nullable=True,
               comment='Standard Augur Metadata',
               schema='augur_data')
    op.alter_column('topic_model_meta', 'data_collection_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='augur_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('topic_model_meta', 'data_collection_date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='augur_data')
    op.alter_column('topic_model_meta', 'data_source',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='Standard Augur Metadata',
               schema='augur_data')
    op.alter_column('topic_model_meta', 'tool_version',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='Standard Augur Metadata',
               schema='augur_data')
    op.alter_column('topic_model_meta', 'tool_source',
               existing_type=sa.VARCHAR(),
               nullable=False,
               comment=None,
               existing_comment='Standard Augur Metadata',
               schema='augur_data')
    op.alter_column('topic_model_meta', 'training_end_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When training ended',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'training_start_time',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When training started',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'visualization_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON object containing visualization data for the model',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'data_fingerprint',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Fingerprint of training data',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'training_message_count',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Number of messages used for training',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'quality',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Quality metrics',
               existing_nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"),
               schema='augur_data')
    op.alter_column('topic_model_meta', 'topic_diversity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Topic diversity score',
               existing_nullable=False,
               existing_server_default=sa.text('0.0'),
               schema='augur_data')
    op.alter_column('topic_model_meta', 'perplexity_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Perplexity score of the model',
               existing_nullable=False,
               existing_server_default=sa.text('0.0'),
               schema='augur_data')
    op.alter_column('topic_model_meta', 'coherence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Coherence score of the model',
               existing_nullable=False,
               existing_server_default=sa.text('0.0'),
               schema='augur_data')
    op.alter_column('topic_model_meta', 'parameters_hash',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Hash of parameters for deduplication',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'model_file_paths',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON object containing paths to model artifacts',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'training_parameters',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='JSON object containing training parameters',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'num_words_per_topic',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of words per topic',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'num_topics',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Number of topics in the model',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'model_method',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment="Method used for topic modeling (e.g., 'NMF_COUNT', 'LDA_TFIDF')",
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'repo_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               comment=None,
               existing_comment='Repository this model was trained on',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('topic_model_meta', 'model_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Unique identifier for the topic model',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'),
               schema='augur_data')
    op.alter_column('topic_model_event', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Event payload data',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_event', 'level',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Log level (INFO, WARNING, ERROR, etc.)',
               existing_nullable=False,
               existing_server_default=sa.text("'INFO'::text"),
               schema='augur_data')
    op.alter_column('topic_model_event', 'event',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Event type or name',
               existing_nullable=False,
               schema='augur_data')
    op.alter_column('topic_model_event', 'model_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Topic model associated with this event',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('topic_model_event', 'repo_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Repository associated with this event',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('topic_model_event', 'ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Timestamp when the event occurred',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'),
               schema='augur_data')
    op.alter_column('topic_model_event', 'event_id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Unique identifier for the event',
               existing_nullable=False,
               autoincrement=True,
               schema='augur_data')
    # ### end Alembic commands ###
