"""add repo aliases table

Revision ID: 38
Revises: 37
Create Date: 2025-12-15 15:50:31.819780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38'
down_revision = '37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo_aliases',
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('git_url', sa.String(), nullable=False),
    sa.Column('date_collected', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['augur_data.repo.repo_id'], ),
    sa.PrimaryKeyConstraint('repo_id', 'git_url'),
    schema='augur_data'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_aliases', schema='augur_data')
    # ### end Alembic commands ###
