"""sync model with migrations

Revision ID: 38
Revises: 37
Create Date: 2025-12-03 14:32:27.712839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38'
down_revision = '37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('GH-UNIQUE-C', 'contributors', ['gh_login'], deferrable=True, initially='DEFERRED', schema='augur_data')
    op.create_unique_constraint('GL-cntrb-LOGIN-UNIQUE', 'contributors', ['cntrb_login'], schema='augur_data')
    op.create_foreign_key('fk_commits_contributors_3', 'commits', 'contributors', ['cmt_author_platform_username'], ['cntrb_login'], source_schema='augur_data', referent_schema='augur_data', onupdate='CASCADE', ondelete='CASCADE', initially='DEFERRED', deferrable=True)
    op.drop_constraint(op.f('pr_review_unique'), 'pull_request_reviews', schema='augur_data', type_='unique')
    op.create_unique_constraint('pr_review_unique', 'pull_request_reviews', ['pr_review_src_id', 'tool_source'], schema='augur_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pr_review_unique', 'pull_request_reviews', schema='augur_data', type_='unique')
    op.create_unique_constraint(op.f('pr_review_unique'), 'pull_request_reviews', ['pr_review_src_id'], schema='augur_data')
    op.drop_constraint('fk_commits_contributors_3', 'commits', schema='augur_data', type_='foreignkey')
    op.drop_constraint('GL-cntrb-LOGIN-UNIQUE', 'contributors', schema='augur_data', type_='unique')
    op.drop_constraint('GH-UNIQUE-C', 'contributors', schema='augur_data', type_='unique')
    # ### end Alembic commands ###
