"""remove redundant uniqueness check

Revision ID: 39
Revises: 38
Create Date: 2026-02-18 10:46:16.413579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39'
down_revision = '38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique-prx'), 'pull_requests', schema='augur_data', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique-prx'), 'pull_requests', ['repo_id', 'pr_src_id'], schema='augur_data')
    # ### end Alembic commands ###
