"""remove unused api url fields in contributors table

Revision ID: 39
Revises: 38
Create Date: 2026-03-02 15:49:34.325165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39'
down_revision = '38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contributors', 'gh_url',
               existing_type=sa.VARCHAR(),
               comment='Convenience url to aid in manually debugging database and sanity checking against GitHub API results (tools like dbeaver make links like this clickable). May be removed in the future.',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('contributors', 'gh_html_url',
               existing_type=sa.VARCHAR(),
               comment='Convenience url to aid in manually debugging database and sanity checking against GitHub API results (tools like dbeaver make links like this clickable). May be removed in the future.',
               existing_nullable=True,
               schema='augur_data')
    op.drop_column('contributors', 'gh_starred_url', schema='augur_data')
    op.drop_column('contributors', 'gh_organizations_url', schema='augur_data')
    op.drop_column('contributors', 'gh_repos_url', schema='augur_data')
    op.drop_column('contributors', 'gh_followers_url', schema='augur_data')
    op.drop_column('contributors', 'gh_subscriptions_url', schema='augur_data')
    op.drop_column('contributors', 'gh_received_events_url', schema='augur_data')
    op.drop_column('contributors', 'gh_gists_url', schema='augur_data')
    op.drop_column('contributors', 'gh_following_url', schema='augur_data')
    op.drop_column('contributors', 'gh_events_url', schema='augur_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contributors', sa.Column('gh_events_url', sa.VARCHAR(), autoincrement=False, nullable=True), schema='augur_data')
    op.add_column('contributors', sa.Column('gh_following_url', sa.VARCHAR(), autoincrement=False, nullable=True), schema='augur_data')
    op.add_column('contributors', sa.Column('gh_gists_url', sa.VARCHAR(), autoincrement=False, nullable=True), schema='augur_data')
    op.add_column('contributors', sa.Column('gh_received_events_url', sa.VARCHAR(), autoincrement=False, nullable=True), schema='augur_data')
    op.add_column('contributors', sa.Column('gh_subscriptions_url', sa.VARCHAR(), autoincrement=False, nullable=True), schema='augur_data')
    op.add_column('contributors', sa.Column('gh_followers_url', sa.VARCHAR(), autoincrement=False, nullable=True), schema='augur_data')
    op.add_column('contributors', sa.Column('gh_repos_url', sa.VARCHAR(), autoincrement=False, nullable=True), schema='augur_data')
    op.add_column('contributors', sa.Column('gh_organizations_url', sa.VARCHAR(), autoincrement=False, nullable=True), schema='augur_data')
    op.add_column('contributors', sa.Column('gh_starred_url', sa.VARCHAR(), autoincrement=False, nullable=True), schema='augur_data')
    op.alter_column('contributors', 'gh_html_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Convenience url to aid in manually debugging database and sanity checking against GitHub API results (tools like dbeaver make links like this clickable). May be removed in the future.',
               existing_nullable=True,
               schema='augur_data')
    op.alter_column('contributors', 'gh_url',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='Convenience url to aid in manually debugging database and sanity checking against GitHub API results (tools like dbeaver make links like this clickable). May be removed in the future.',
               existing_nullable=True,
               schema='augur_data')
    # ### end Alembic commands ###
