"""selectively drop test table

Revision ID: 39
Revises: 38
Create Date: 2026-02-17 16:01:29.379433

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '39'
down_revision = '38'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()
    # the db init script added in #3351 includes this table in the public schema for some reason
    # databases created after that pr was merged will have this extraneous table, so we should drop it.
    if "test" in tables: 
        op.drop_table('test')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('test', sa.VARCHAR(length=255), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###