"""Hello, Alembic

Revision ID: 4dbade803ba1
Revises: 73ebe53353af
Create Date: 2022-06-02 03:47:47.500278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1"
down_revision = "0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issue_reporter_created_at",
        sa.Column("reporter_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(precision=0), nullable=True),
        sa.Column("repo_id", sa.BigInteger(), nullable=True),
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_issue_reporter_created_at_repo_id"),
        "issue_reporter_created_at",
        ["repo_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index("repos_id", table_name="analysis_log", schema="augur_data")
    op.create_index(
        op.f("ix_augur_data_analysis_log_repos_id"),
        "analysis_log",
        ["repos_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        "commit_parents_ibfk_1", table_name="commit_parents", schema="augur_data"
    )
    op.drop_index(
        "commit_parents_ibfk_2", table_name="commit_parents", schema="augur_data"
    )
    op.create_index(
        op.f("ix_augur_data_commit_parents_cmt_id"),
        "commit_parents",
        ["cmt_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_commit_parents_parent_id"),
        "commit_parents",
        ["parent_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index("author_affiliation", table_name="commits", schema="augur_data")
    op.drop_index("author_cntrb_id", table_name="commits", schema="augur_data")
    op.drop_index("author_raw_email", table_name="commits", schema="augur_data")
    op.drop_index("commited", table_name="commits", schema="augur_data")
    op.drop_index("committer_affiliation", table_name="commits", schema="augur_data")
    op.drop_index("committer_raw_email", table_name="commits", schema="augur_data")
    op.create_index(
        op.f("ix_augur_data_commits_cmt_author_affiliation"),
        "commits",
        ["cmt_author_affiliation"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_commits_cmt_author_raw_email"),
        "commits",
        ["cmt_author_raw_email"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_commits_cmt_committer_affiliation"),
        "commits",
        ["cmt_committer_affiliation"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_commits_cmt_committer_raw_email"),
        "commits",
        ["cmt_committer_raw_email"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_commits_cmt_ght_author_id"),
        "commits",
        ["cmt_ght_author_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_commits_cmt_id"),
        "commits",
        ["cmt_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index("cnt-fullname", table_name="contributors", schema="augur_data")
    op.drop_index("cntrb-theemail", table_name="contributors", schema="augur_data")
    op.drop_index(
        "cntrb_canonica-idx11", table_name="contributors", schema="augur_data"
    )
    op.drop_index(
        "cntrb_login_platform_index", table_name="contributors", schema="augur_data"
    )
    op.drop_index(
        "contributor_worker_email_finder",
        table_name="contributors",
        schema="augur_data",
    )
    op.drop_index(
        "contributor_worker_fullname_finder",
        table_name="contributors",
        schema="augur_data",
    )
    op.drop_index(
        "contributors_idx_cntrb_email3", table_name="contributors", schema="augur_data"
    )
    op.drop_index("login", table_name="contributors", schema="augur_data")
    op.drop_index(
        "login-contributor-idx", table_name="contributors", schema="augur_data"
    )
    op.create_index(
        op.f("ix_augur_data_contributors_cntrb_canonical"),
        "contributors",
        ["cntrb_canonical"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_contributors_cntrb_email"),
        "contributors",
        ["cntrb_email"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_contributors_cntrb_full_name"),
        "contributors",
        ["cntrb_full_name"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        "issue-cntrb-assign-idx-1", table_name="issue_assignees", schema="augur_data"
    )
    op.create_index(
        op.f("ix_augur_data_issue_assignees_cntrb_id"),
        "issue_assignees",
        ["cntrb_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index("issue-cntrb-idx2", table_name="issue_events", schema="augur_data")
    op.drop_index("issue_events_ibfk_1", table_name="issue_events", schema="augur_data")
    op.drop_index("issue_events_ibfk_2", table_name="issue_events", schema="augur_data")
    op.create_index(
        op.f("ix_augur_data_issue_events_cntrb_id"),
        "issue_events",
        ["cntrb_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_issue_events_issue_event_src_id"),
        "issue_events",
        ["issue_event_src_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_issue_events_issue_id"),
        "issue_events",
        ["issue_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index("issue-cntrb-dix2", table_name="issues", schema="augur_data")
    op.drop_index("issues_ibfk_1", table_name="issues", schema="augur_data")
    op.drop_index("issues_ibfk_2", table_name="issues", schema="augur_data")
    op.drop_index("issues_ibfk_4", table_name="issues", schema="augur_data")
    op.create_index(
        op.f("ix_augur_data_issues_cntrb_id"),
        "issues",
        ["cntrb_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_issues_pull_request_id"),
        "issues",
        ["pull_request_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_issues_repo_id"),
        "issues",
        ["repo_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_issues_reporter_id"),
        "issues",
        ["reporter_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index("REPO_DEP", table_name="library_dependencies", schema="augur_data")
    op.create_index(
        op.f("ix_augur_data_library_dependencies_library_id"),
        "library_dependencies",
        ["library_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index("msg-cntrb-id-idx", table_name="message", schema="augur_data")
    op.create_index(
        op.f("ix_augur_data_message_cntrb_id"),
        "message",
        ["cntrb_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index("plat", table_name="platform", schema="augur_data")
    op.create_unique_constraint(None, "platform", ["pltfrm_id"], schema="augur_data")
    op.drop_index(
        "pr_anal_idx", table_name="pull_request_analysis", schema="augur_data"
    )
    op.drop_index(
        "probability_idx", table_name="pull_request_analysis", schema="augur_data"
    )
    op.create_index(
        op.f("ix_augur_data_pull_request_analysis_merge_probability"),
        "pull_request_analysis",
        ["merge_probability"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_pull_request_analysis_pull_request_id"),
        "pull_request_analysis",
        ["pull_request_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        "pr_meta_cntrb-idx", table_name="pull_request_assignees", schema="augur_data"
    )
    op.create_index(
        op.f("ix_augur_data_pull_request_assignees_contrib_id"),
        "pull_request_assignees",
        ["contrib_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        "pr_events_ibfk_1", table_name="pull_request_events", schema="augur_data"
    )
    op.drop_index(
        "pr_events_ibfk_2", table_name="pull_request_events", schema="augur_data"
    )
    op.create_index(
        op.f("ix_augur_data_pull_request_events_cntrb_id"),
        "pull_request_events",
        ["cntrb_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_pull_request_events_pull_request_id"),
        "pull_request_events",
        ["pull_request_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        "pr_meta-cntrbid-idx", table_name="pull_request_meta", schema="augur_data"
    )
    op.create_index(
        op.f("ix_augur_data_pull_request_meta_cntrb_id"),
        "pull_request_meta",
        ["cntrb_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        "pr-cntrb-idx-repo", table_name="pull_request_repo", schema="augur_data"
    )
    op.create_index(
        op.f("ix_augur_data_pull_request_repo_pr_cntrb_id"),
        "pull_request_repo",
        ["pr_cntrb_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        "pr-reviewers-cntrb-idx1",
        table_name="pull_request_reviewers",
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_pull_request_reviewers_cntrb_id"),
        "pull_request_reviewers",
        ["cntrb_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index("forked", table_name="repo", schema="augur_data")
    op.drop_index("repogitindexrep", table_name="repo", schema="augur_data")
    op.drop_index("reponameindex", table_name="repo", schema="augur_data")
    op.drop_index("reponameindexbtree", table_name="repo", schema="augur_data")
    op.drop_index("rggrouponrepoindex", table_name="repo", schema="augur_data")
    op.drop_index("therepo", table_name="repo", schema="augur_data")
    op.create_index(
        op.f("ix_augur_data_repo_forked_from"),
        "repo",
        ["forked_from"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_repo_repo_git"),
        "repo",
        ["repo_git"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_repo_repo_group_id"),
        "repo",
        ["repo_group_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        op.f("ix_augur_data_repo_repo_name"),
        "repo",
        ["repo_name"],
        unique=False,
        schema="augur_data",
    )
    op.create_unique_constraint(None, "repo", ["repo_id"], schema="augur_data")
    op.drop_index("rgidm", table_name="repo_groups", schema="augur_data")
    op.drop_index("rgnameindex", table_name="repo_groups", schema="augur_data")
    op.create_index(
        op.f("ix_augur_data_repo_groups_rg_name"),
        "repo_groups",
        ["rg_name"],
        unique=False,
        schema="augur_data",
    )
    op.create_unique_constraint(
        None, "repo_groups", ["repo_group_id"], schema="augur_data"
    )
    op.drop_index("dater", table_name="repo_insights_records", schema="augur_data")
    op.create_index(
        op.f("ix_augur_data_repo_insights_records_ri_date"),
        "repo_insights_records",
        ["ri_date"],
        unique=False,
        schema="augur_data",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_augur_data_repo_insights_records_ri_date"),
        table_name="repo_insights_records",
        schema="augur_data",
    )
    op.create_index(
        "dater", "repo_insights_records", ["ri_date"], unique=False, schema="augur_data"
    )
    op.drop_constraint(None, "repo_groups", schema="augur_data", type_="unique")
    op.drop_index(
        op.f("ix_augur_data_repo_groups_rg_name"),
        table_name="repo_groups",
        schema="augur_data",
    )
    op.create_index(
        "rgnameindex", "repo_groups", ["rg_name"], unique=False, schema="augur_data"
    )
    op.create_index(
        "rgidm", "repo_groups", ["repo_group_id"], unique=False, schema="augur_data"
    )
    op.drop_constraint(None, "repo", schema="augur_data", type_="unique")
    op.drop_index(
        op.f("ix_augur_data_repo_repo_name"), table_name="repo", schema="augur_data"
    )
    op.drop_index(
        op.f("ix_augur_data_repo_repo_group_id"), table_name="repo", schema="augur_data"
    )
    op.drop_index(
        op.f("ix_augur_data_repo_repo_git"), table_name="repo", schema="augur_data"
    )
    op.drop_index(
        op.f("ix_augur_data_repo_forked_from"), table_name="repo", schema="augur_data"
    )
    op.create_index("therepo", "repo", ["repo_id"], unique=False, schema="augur_data")
    op.create_index(
        "rggrouponrepoindex",
        "repo",
        ["repo_group_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "reponameindexbtree", "repo", ["repo_name"], unique=False, schema="augur_data"
    )
    op.create_index(
        "reponameindex", "repo", ["repo_name"], unique=False, schema="augur_data"
    )
    op.create_index(
        "repogitindexrep", "repo", ["repo_git"], unique=False, schema="augur_data"
    )
    op.create_index(
        "forked", "repo", ["forked_from"], unique=False, schema="augur_data"
    )
    op.drop_index(
        op.f("ix_augur_data_pull_request_reviewers_cntrb_id"),
        table_name="pull_request_reviewers",
        schema="augur_data",
    )
    op.create_index(
        "pr-reviewers-cntrb-idx1",
        "pull_request_reviewers",
        ["cntrb_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_pull_request_repo_pr_cntrb_id"),
        table_name="pull_request_repo",
        schema="augur_data",
    )
    op.create_index(
        "pr-cntrb-idx-repo",
        "pull_request_repo",
        ["pr_cntrb_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_pull_request_meta_cntrb_id"),
        table_name="pull_request_meta",
        schema="augur_data",
    )
    op.create_index(
        "pr_meta-cntrbid-idx",
        "pull_request_meta",
        ["cntrb_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_pull_request_events_pull_request_id"),
        table_name="pull_request_events",
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_pull_request_events_cntrb_id"),
        table_name="pull_request_events",
        schema="augur_data",
    )
    op.create_index(
        "pr_events_ibfk_2",
        "pull_request_events",
        ["cntrb_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "pr_events_ibfk_1",
        "pull_request_events",
        ["pull_request_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_pull_request_assignees_contrib_id"),
        table_name="pull_request_assignees",
        schema="augur_data",
    )
    op.create_index(
        "pr_meta_cntrb-idx",
        "pull_request_assignees",
        ["contrib_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_pull_request_analysis_pull_request_id"),
        table_name="pull_request_analysis",
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_pull_request_analysis_merge_probability"),
        table_name="pull_request_analysis",
        schema="augur_data",
    )
    op.create_index(
        "probability_idx",
        "pull_request_analysis",
        ["merge_probability"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "pr_anal_idx",
        "pull_request_analysis",
        ["pull_request_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_constraint(None, "platform", schema="augur_data", type_="unique")
    op.create_index(
        "plat", "platform", ["pltfrm_id"], unique=False, schema="augur_data"
    )
    op.drop_index(
        op.f("ix_augur_data_message_cntrb_id"),
        table_name="message",
        schema="augur_data",
    )
    op.create_index(
        "msg-cntrb-id-idx", "message", ["cntrb_id"], unique=False, schema="augur_data"
    )
    op.drop_index(
        op.f("ix_augur_data_library_dependencies_library_id"),
        table_name="library_dependencies",
        schema="augur_data",
    )
    op.create_index(
        "REPO_DEP",
        "library_dependencies",
        ["library_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_issues_reporter_id"),
        table_name="issues",
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_issues_repo_id"), table_name="issues", schema="augur_data"
    )
    op.drop_index(
        op.f("ix_augur_data_issues_pull_request_id"),
        table_name="issues",
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_issues_cntrb_id"), table_name="issues", schema="augur_data"
    )
    op.create_index(
        "issues_ibfk_4",
        "issues",
        ["pull_request_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "issues_ibfk_2", "issues", ["reporter_id"], unique=False, schema="augur_data"
    )
    op.create_index(
        "issues_ibfk_1", "issues", ["repo_id"], unique=False, schema="augur_data"
    )
    op.create_index(
        "issue-cntrb-dix2", "issues", ["cntrb_id"], unique=False, schema="augur_data"
    )
    op.drop_index(
        op.f("ix_augur_data_issue_events_issue_id"),
        table_name="issue_events",
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_issue_events_issue_event_src_id"),
        table_name="issue_events",
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_issue_events_cntrb_id"),
        table_name="issue_events",
        schema="augur_data",
    )
    op.create_index(
        "issue_events_ibfk_2",
        "issue_events",
        ["cntrb_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "issue_events_ibfk_1",
        "issue_events",
        ["issue_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "issue-cntrb-idx2",
        "issue_events",
        ["issue_event_src_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_issue_assignees_cntrb_id"),
        table_name="issue_assignees",
        schema="augur_data",
    )
    op.create_index(
        "issue-cntrb-assign-idx-1",
        "issue_assignees",
        ["cntrb_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_contributors_cntrb_full_name"),
        table_name="contributors",
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_contributors_cntrb_email"),
        table_name="contributors",
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_contributors_cntrb_canonical"),
        table_name="contributors",
        schema="augur_data",
    )
    op.create_index(
        "login-contributor-idx",
        "contributors",
        ["cntrb_login"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "login", "contributors", ["cntrb_login"], unique=False, schema="augur_data"
    )
    op.create_index(
        "contributors_idx_cntrb_email3",
        "contributors",
        ["cntrb_email"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "contributor_worker_fullname_finder",
        "contributors",
        ["cntrb_full_name"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "contributor_worker_email_finder",
        "contributors",
        ["cntrb_email"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "cntrb_login_platform_index",
        "contributors",
        ["cntrb_login"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "cntrb_canonica-idx11",
        "contributors",
        ["cntrb_canonical"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "cntrb-theemail",
        "contributors",
        ["cntrb_email"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "cnt-fullname",
        "contributors",
        ["cntrb_full_name"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_commits_cmt_id"), table_name="commits", schema="augur_data"
    )
    op.drop_index(
        op.f("ix_augur_data_commits_cmt_ght_author_id"),
        table_name="commits",
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_commits_cmt_committer_raw_email"),
        table_name="commits",
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_commits_cmt_committer_affiliation"),
        table_name="commits",
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_commits_cmt_author_raw_email"),
        table_name="commits",
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_commits_cmt_author_affiliation"),
        table_name="commits",
        schema="augur_data",
    )
    op.create_index(
        "committer_raw_email",
        "commits",
        ["cmt_committer_raw_email"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "committer_affiliation",
        "commits",
        ["cmt_committer_affiliation"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "commited", "commits", ["cmt_id"], unique=False, schema="augur_data"
    )
    op.create_index(
        "author_raw_email",
        "commits",
        ["cmt_author_raw_email"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "author_cntrb_id",
        "commits",
        ["cmt_ght_author_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "author_affiliation",
        "commits",
        ["cmt_author_affiliation"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_commit_parents_parent_id"),
        table_name="commit_parents",
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_commit_parents_cmt_id"),
        table_name="commit_parents",
        schema="augur_data",
    )
    op.create_index(
        "commit_parents_ibfk_2",
        "commit_parents",
        ["parent_id"],
        unique=False,
        schema="augur_data",
    )
    op.create_index(
        "commit_parents_ibfk_1",
        "commit_parents",
        ["cmt_id"],
        unique=False,
        schema="augur_data",
    )
    op.drop_index(
        op.f("ix_augur_data_analysis_log_repos_id"),
        table_name="analysis_log",
        schema="augur_data",
    )
    op.create_index(
        "repos_id", "analysis_log", ["repos_id"], unique=False, schema="augur_data"
    )
    op.drop_index(
        op.f("ix_augur_data_issue_reporter_created_at_repo_id"),
        table_name="issue_reporter_created_at",
        schema="augur_data",
    )
    op.drop_table("issue_reporter_created_at", schema="augur_data")
    # ### end Alembic commands ###
