"""Remove unneeded repo unique

Revision ID: 4
Revises: 3
Create Date: 2022-07-11 09:39:57.032351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4'
down_revision = '3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('therepo', table_name='repo', schema='augur_data')
    op.create_unique_constraint(None, 'repo', ['repo_id'], schema='augur_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'repo', schema='augur_data', type_='unique')
    op.create_index('therepo', 'repo', ['repo_id'], unique=False, schema='augur_data')
    # ### end Alembic commands ###
