"""Remove unneeded contributor indexes

Revision ID: 3
Revises: 2
Create Date: 2022-07-11 09:29:47.596614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3'
down_revision = '2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('login', table_name='contributors', schema='augur_data')
    op.drop_index('login-contributor-idx', table_name='contributors', schema='augur_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('login-contributor-idx', 'contributors', ['cntrb_login'], unique=False, schema='augur_data')
    op.create_index('login', 'contributors', ['cntrb_login'], unique=False, schema='augur_data')
    # ### end Alembic commands ###
