-- #SPDX-License-Identifier: MIT
BEGIN;
INSERT INTO "augur_data"."platform" VALUES (25150, 'GitHub', '3', '2019-06-05', 'Manual Entry', 'Sean Goggins', 'GitHub', '2019-06-05 17:23:42');
COMMIT;

INSERT INTO "augur_data"."contributors"("cntrb_id", "cntrb_login", "cntrb_email", "cntrb_company", "cntrb_created_at", "cntrb_type", "cntrb_fake", "cntrb_deleted", "cntrb_long", "cntrb_lat", "cntrb_country_code", "cntrb_state", "cntrb_city", "cntrb_location", "cntrb_canonical", "gh_user_id", "gh_login", "gh_url", "gh_html_url", "gh_node_id", "gh_avatar_url", "gh_gravatar_id", "gh_followers_url", "gh_following_url", "gh_gists_url", "gh_starred_url", "gh_subscriptions_url", "gh_organizations_url", "gh_repos_url", "gh_events_url", "gh_received_events_url", "gh_type", "gh_site_admin", "tool_source", "tool_version", "data_source", "data_collection_date") VALUES (1, 'not-provided', NULL, NULL, '2019-06-13 11:33:39', NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'nobody', 'http://fake.me', 'http://fake.me', 'x', 'http://fake.me', NULL, 'http://fake.me', 'http://fake.me', 'http://fake.me', 'http://fake.me', 'http://fake.me', 'http://fake.me', 'http://fake.me', 'http://fake.me', NULL, NULL, NULL, NULL, NULL, NULL, '2019-06-13 16:35:25');

INSERT INTO "augur_data"."repo_groups"("repo_group_id", "rg_name", "rg_description", "rg_website", "rg_recache", "rg_last_modified", "rg_type", "tool_source", "tool_version", "data_source", "data_collection_date") VALUES (1, 'Default Repo Group', 'The default repo group created by the schema generation script', '', 0, '2019-06-03 15:55:20', 'GitHub Organization', 'load', 'one', 'git', '2019-06-05 13:36:25');
INSERT INTO "augur_data"."repo"("repo_id", "repo_group_id", "repo_git", "repo_path", "repo_name", "repo_added", "repo_status", "repo_type", "url", "owner_id", "description", "primary_language", "created_at", "forked_from", "updated_at", "tool_source", "tool_version", "data_source", "data_collection_date") VALUES (1, 1, 'https://github.com/chaoss/augur.git', 'github.com/chaoss/', 'augur', '2019-05-31 14:28:44', 'New', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'data load', 'one', 'git', '2019-06-05 18:41:14');


-- ----------------------------
-- Records of settings
-- ----------------------------
BEGIN;
INSERT INTO "augur_data"."settings" VALUES (5, 'report_date', 'committer', '2019-05-07 12:47:26');
INSERT INTO "augur_data"."settings" VALUES (6, 'report_attribution', 'author', '2019-05-07 12:47:26');
INSERT INTO "augur_data"."settings" VALUES (10, 'google_analytics', 'disabled', '2019-05-07 12:47:26');
INSERT INTO "augur_data"."settings" VALUES (11, 'update_frequency', '24', '2019-05-07 12:47:26');
INSERT INTO "augur_data"."settings" VALUES (12, 'database_version', '7', '2019-05-07 12:47:26');
INSERT INTO "augur_data"."settings" VALUES (13, 'results_visibility', 'show', '2019-05-07 12:47:26');
INSERT INTO "augur_data"."settings" VALUES (1, 'start_date', '2001-01-01', '1900-01-22 20:34:51');
INSERT INTO "augur_data"."settings" VALUES (4, 'log_level', 'Debug', '2019-05-07 12:47:26');
INSERT INTO "augur_data"."settings" VALUES (2, 'repo_directory', '/augur/repos/', '2019-05-07 12:47:26');
INSERT INTO "augur_data"."settings" VALUES (8, 'affiliations_processed', '2001-08-26 10:03:29.815013+00', '1900-01-22 20:36:27');
INSERT INTO "augur_data"."settings" VALUES (9, 'aliases_processed', '2001-08-26 10:03:29.815013+00', '1900-01-22 20:36:27');
INSERT INTO "augur_data"."settings" VALUES (7, 'working_author', 'done', '1900-01-22 20:23:43');
INSERT INTO "augur_data"."settings" VALUES (3, 'utility_status', 'Idle', '1900-01-22 20:38:07');

COMMIT;



-- ----------------------------
-- Records of chaoss_metric_status
-- ----------------------------
BEGIN;
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (2, 'growth-maturity-decline', 'githubapi', 'timeseries', 'implemented', 'unimplemented', 't', '/api/unstable/<owner>/<repo>/timeseries/githubapi/issues', NULL, 'Open Issues', 'growth-maturity-decline', '"open-issues"', 'Insight Worker', '0.0.1', 'githubapi', '2019-06-20 22:41:41', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (3, 'growth-maturity-decline', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/timeseries/issues', NULL, 'Open Issues', 'growth-maturity-decline', '"open-issues"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:42:15', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (4, 'growth-maturity-decline', 'githubapi', 'timeseries', 'implemented', 'unimplemented', 't', '/api/unstable/<owner>/<repo>/timeseries/githubapi/issues/closed', NULL, 'Closed Issues', 'growth-maturity-decline', '"closed-issues"', 'Insight Worker', '0.0.1', 'githubapi', '2019-06-20 22:45:53', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (5, 'growth-maturity-decline', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/timeseries/issues/closed', NULL, 'Closed Issues', 'growth-maturity-decline', '"closed-issues"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:49:26', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (6, 'growth-maturity-decline', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/timeseries/issues/response_time', NULL, 'First Response To Issue Duration', 'growth-maturity-decline', '"first-response-to-issue-duration"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:49:27', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (7, 'growth-maturity-decline', 'githubapi', 'timeseries', 'implemented', 'unimplemented', 't', '/api/unstable/<owner>/<repo>/timeseries/githubapi/commits', NULL, 'Code Commits', 'growth-maturity-decline', '"code-commits"', 'Insight Worker', '0.0.1', 'githubapi', '2019-06-20 22:49:29', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (8, 'growth-maturity-decline', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/timeseries/commits', NULL, 'Code Commits', 'growth-maturity-decline', '"code-commits"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:49:30', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (9, 'growth-maturity-decline', 'githubapi', 'metric', 'implemented', 'unimplemented', 't', '/api/unstable/<owner>/<repo>/lines_changed', NULL, 'Lines Of Code Changed', 'growth-maturity-decline', '"lines-of-code-changed"', 'Insight Worker', '0.0.1', 'githubapi', '2019-06-20 22:49:32', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (10, 'growth-maturity-decline', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/timeseries/pulls/maintainer_response_time', NULL, 'Maintainer Response To Merge Request Duration', 'growth-maturity-decline', '"maintainer-response-to-merge-request-duration"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:49:33', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (11, 'growth-maturity-decline', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/timeseries/code_review_iteration', NULL, 'Code Review Iteration', 'growth-maturity-decline', '"code-review-iteration"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:49:35', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (12, 'growth-maturity-decline', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/timeseries/forks', NULL, 'Forks', 'growth-maturity-decline', '"forks"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:49:36', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (13, 'growth-maturity-decline', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/timeseries/pulls', NULL, 'Pull Requests Open', 'growth-maturity-decline', '"pull-requests-open"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:49:38', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (14, 'growth-maturity-decline', 'ghtorrent', 'timeseries', 'implemented', 'unimplemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/pulls/closed', NULL, 'Pull Requests Closed', 'growth-maturity-decline', '"pull-requests-closed"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:49:39', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (15, 'growth-maturity-decline', 'ghtorrent', 'timeseries', 'implemented', 'unimplemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/pulls/response_time', NULL, 'Pull Request Comment Duration', 'growth-maturity-decline', '"pull-request-comment-duration"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:49:41', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (16, 'growth-maturity-decline', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/timeseries/pulls/comments', NULL, 'Pull Request Comments', 'growth-maturity-decline', '"pull-request-comments"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:49:42', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (17, 'growth-maturity-decline', 'augur_db', 'metric', 'implemented', 'unimplemented', 't', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/contributors', NULL, 'Contributors', 'growth-maturity-decline', '"contributors"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:49:44', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (18, 'growth-maturity-decline', 'githubapi', 'metric', 'implemented', 'unimplemented', 't', '/api/unstable/<owner>/<repo>/githubapi/contributors', NULL, 'Contributors', 'growth-maturity-decline', '"contributors"', 'Insight Worker', '0.0.1', 'githubapi', '2019-06-20 22:49:45', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (19, 'growth-maturity-decline', 'ghtorrent', 'metric', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/contributors', NULL, 'Contributors', 'growth-maturity-decline', '"contributors"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:49:47', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (20, 'growth-maturity-decline', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/timeseries/community_engagement', NULL, 'Community Engagement', 'growth-maturity-decline', '"community-engagement"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:49:48', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (21, 'growth-maturity-decline', 'augur_db', 'metric', 'implemented', 'unimplemented', 't', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/sub-projects', NULL, 'Sub Projects', 'growth-maturity-decline', '"sub-projects"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:49:50', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (22, 'growth-maturity-decline', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/timeseries/contribution_acceptance', NULL, 'Contribution Acceptance', 'growth-maturity-decline', '"contribution-acceptance"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:49:51', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (23, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/code-changes', NULL, 'Code Changes', 'experimental', '"code-changes"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:49:53', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (24, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/pull-requests-merge-contributor-new', NULL, 'Pull Requests Merge Contributor New', 'experimental', '"pull-requests-merge-contributor-new"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:49:55', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (25, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/issues-first-time-opened', NULL, 'Issues First Time Opened', 'experimental', '"issues-first-time-opened"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:49:56', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (26, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/issues-first-time-closed', NULL, 'Issues First Time Closed', 'experimental', '"issues-first-time-closed"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:49:58', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (27, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/contributors-new', NULL, 'Contributors New', 'experimental', '"contributors-new"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:49:59', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (28, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/code-changes-lines', NULL, 'Code Changes Lines', 'experimental', '"code-changes-lines"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:50:01', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (29, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/issues-new', NULL, 'Issues New', 'experimental', '"issues-new"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:50:02', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (30, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/issues-closed', NULL, 'Issues Closed', 'experimental', '"issues-closed"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:50:04', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (31, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', 'none', NULL, 'Issue Duration', 'experimental', '"issue-duration"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:50:05', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (32, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/issue-backlog', NULL, 'Issue Backlog', 'experimental', '"issue-backlog"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:50:07', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (33, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/issues-open-age', NULL, 'Issues Open Age', 'experimental', '"issues-open-age"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:50:08', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (34, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/issues-closed-resolution-duration', NULL, 'Issues Closed Resolution Duration', 'experimental', '"issues-closed-resolution-duration"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:50:10', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (35, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', 'none', NULL, 'Lines Changed By Author', 'experimental', '"lines-changed-by-author"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:50:11', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (36, 'experimental', 'augur_db', 'git', 'implemented', 'unimplemented', 'f', '/api/unstable/repo-groups', NULL, 'Repo Groups', 'experimental', '"repo-groups"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:50:13', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (37, 'experimental', 'augur_db', 'git', 'implemented', 'unimplemented', 'f', '/api/unstable/repos', NULL, 'Downloaded Repos', 'experimental', '"downloaded-repos"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:50:15', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (38, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/open-issues-count', NULL, 'Open Issues Count', 'experimental', '"closed-issues-count"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:50:16', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (39, 'experimental', 'augur_db', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/repo-groups/<repo_group_id>/repos/<repo_id>/closed-issues-count', NULL, 'Closed Issues Count', 'experimental', '"closed-issues-count"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:50:18', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (40, 'experimental', 'augur_db', 'git', 'implemented', 'unimplemented', 'f', '/api/unstable/repos/<owner>/<repo>', NULL, 'Get Repo', 'experimental', '"get-repo"', 'Insight Worker', '0.0.1', 'augur_db', '2019-06-20 22:50:19', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (41, 'experimental', 'downloads', 'timeseries', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/downloads', NULL, 'Downloads', 'experimental', '"downloads"', 'Insight Worker', '0.0.1', 'downloads', '2019-06-20 22:50:21', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (42, 'experimental', 'githubapi', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/<owner>/<repo>/githubapi/pull_requests_closed', NULL, 'Pull Requests Closed', 'experimental', '"pull_requests_closed"', 'Insight Worker', '0.0.1', 'githubapi', '2019-06-20 22:50:22', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (43, 'experimental', 'githubapi', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/<owner>/<repo>/githubapi/pull_requests_merged', NULL, 'Pull Requests Merged', 'experimental', '"pull_requests_merged"', 'Insight Worker', '0.0.1', 'githubapi', '2019-06-20 22:50:24', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (44, 'experimental', 'githubapi', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/<owner>/<repo>/githubapi/pull_requests_open', NULL, 'Pull Requests Open', 'experimental', '"pull_requests_open"', 'Insight Worker', '0.0.1', 'githubapi', '2019-06-20 22:50:25', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (45, 'experimental', 'githubapi', 'metric', 'implemented', 'unimplemented', 't', '/api/unstable/<owner>/<repo>/githubapi/repository_size', NULL, 'Repository Size', 'experimental', '"repository-size"', 'Insight Worker', '0.0.1', 'githubapi', '2019-06-20 22:50:27', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (46, 'experimental', 'githubapi', 'metric', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/bus_factor', NULL, 'Bus Factor', 'experimental', '"bus-factor"', 'Insight Worker', '0.0.1', 'githubapi', '2019-06-20 22:50:28', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (47, 'experimental', 'githubapi', 'timeseries', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/tags/major', NULL, 'Major Tags', 'experimental', '"major-tags"', 'Insight Worker', '0.0.1', 'githubapi', '2019-06-20 22:50:30', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (48, 'experimental', 'githubapi', 'timeseries', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/tags', NULL, 'Tags', 'experimental', '"tags"', 'Insight Worker', '0.0.1', 'githubapi', '2019-06-20 22:50:31', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (49, 'experimental', 'facade', 'git', 'implemented', 'unimplemented', 'f', '/api/unstable/git/repos', NULL, 'Downloaded Repos', 'experimental', '"downloaded-repos"', 'Insight Worker', '0.0.1', 'facade', '2019-06-20 22:50:33', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (50, 'experimental', 'facade', 'git', 'implemented', 'implemented', 'f', '/api/unstable/git/changes_by_author', NULL, 'Lines Changed By Author', 'experimental', '"lines-changed-by-author"', 'Insight Worker', '0.0.1', 'facade', '2019-06-20 22:50:35', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (51, 'experimental', 'facade', 'git', 'implemented', 'unimplemented', 'f', '/api/unstable/git/lines_changed_by_week', NULL, 'Lines Changed By Week', 'experimental', '"lines-changed-by-week"', 'Insight Worker', '0.0.1', 'facade', '2019-06-20 22:50:36', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (52, 'experimental', 'facade', 'git', 'implemented', 'unimplemented', 'f', '/api/unstable/git/lines_changed_by_month', NULL, 'Lines Changed By Month', 'experimental', '"lines-changed-by-month"', 'Insight Worker', '0.0.1', 'facade', '2019-06-20 22:50:38', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (53, 'experimental', 'facade', 'git', 'implemented', 'unimplemented', 'f', '/api/unstable/git/commits_by_week', NULL, 'Commits By Week', 'experimental', '"commits-by-week"', 'Insight Worker', '0.0.1', 'facade', '2019-06-20 22:50:40', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (54, 'experimental', 'facade', 'git', 'implemented', 'implemented', 'f', '/api/unstable/git/facade_project', NULL, 'Facade Project', 'experimental', '"facade-project"', 'Insight Worker', '0.0.1', 'facade', '2019-06-20 22:50:41', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (55, 'experimental', 'facade', 'metric', 'implemented', 'unimplemented', 'f', 'none', NULL, 'Annual Commit Count Ranked By New Repo In Repo Group', 'experimental', '"annual-commit-count-ranked-by-new-repo-in-repo-group"', 'Insight Worker', '0.0.1', 'facade', '2019-06-20 22:50:43', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (56, 'experimental', 'facade', 'metric', 'implemented', 'unimplemented', 'f', 'none', NULL, 'Annual Lines Of Code Count Ranked By New Repo In Repo Group', 'experimental', '"annual-lines-of-code-count-ranked-by-new-repo-in-repo-group"', 'Insight Worker', '0.0.1', 'facade', '2019-06-20 22:50:44', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (57, 'experimental', 'facade', 'metric', 'implemented', 'unimplemented', 'f', 'none', NULL, 'Annual Commit Count Ranked By Repo In Repo Group', 'experimental', '"annual-commit-count-ranked-by-repo-in-repo-group"', 'Insight Worker', '0.0.1', 'facade', '2019-06-20 22:50:46', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (58, 'experimental', 'facade', 'metric', 'implemented', 'unimplemented', 'f', 'none', NULL, 'Annual Lines Of Code Count Ranked By Repo In Repo Group', 'experimental', '"annual-lines-of-code-count-ranked-by-repo-in-repo-group"', 'Insight Worker', '0.0.1', 'facade', '2019-06-20 22:50:48', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (59, 'experimental', 'facade', 'metric', 'implemented', 'unimplemented', 'f', 'none', NULL, 'Lines Of Code Commit Counts By Calendar Year Grouped', 'experimental', '"lines-of-code-commit-counts-by-calendar-year-grouped"', 'Insight Worker', '0.0.1', 'facade', '2019-06-20 22:50:49', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (60, 'experimental', 'facade', 'metric', 'implemented', 'unimplemented', 'f', 'none', NULL, 'Unaffiliated Contributors Lines Of Code Commit Counts By Calendar Year Grouped', 'experimental', '"unaffiliated-contributors-lines-of-code-commit-counts-by-calendar-year-grouped"', 'Insight Worker', '0.0.1', 'facade', '2019-06-20 22:50:51', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (61, 'experimental', 'facade', 'metric', 'implemented', 'unimplemented', 'f', 'none', NULL, 'Repo Group Lines Of Code Commit Counts Calendar Year Grouped', 'experimental', '"repo-group-lines-of-code-commit-counts-calendar-year-grouped"', 'Insight Worker', '0.0.1', 'facade', '2019-06-20 22:50:52', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (62, 'experimental', 'ghtorrent', 'metric', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/contributing_github_organizations', NULL, 'Contributing Github Organizations', 'experimental', '"contributing-github-organizations"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:50:54', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (63, 'experimental', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/new_contributing_github_organizations', NULL, 'New Contributing Github Organizations', 'experimental', '"new-contributing-github-organizations"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:50:56', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (64, 'experimental', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/timeseries/issue_comments', NULL, 'Issue Comments', 'experimental', '"issue-comments"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:50:57', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (65, 'experimental', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/timeseries/pulls/made_closed', NULL, 'Pull Requests Made Closed', 'experimental', '"pull-requests-made-closed"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:50:59', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (66, 'experimental', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 't', '/api/unstable/<owner>/<repo>/timeseries/watchers', NULL, 'Watchers', 'experimental', '"watchers"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:51:00', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (67, 'experimental', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/commits100', NULL, 'Commits100', 'experimental', '"commits100"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:51:02', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (68, 'experimental', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/commits/comments', NULL, 'Commit Comments', 'experimental', '"commit-comments"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:51:03', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (69, 'experimental', 'ghtorrent', 'metric', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/committer_locations', NULL, 'Committer Locations', 'experimental', '"committer-locations"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:51:05', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (70, 'experimental', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/total_committers', NULL, 'Total Committers', 'experimental', '"total-committers"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:51:07', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (71, 'experimental', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/issues/activity', NULL, 'Issue Activity', 'experimental', '"issue-activity"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:51:08', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (72, 'experimental', 'ghtorrent', 'timeseries', 'implemented', 'unimplemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/pulls/acceptance_rate', NULL, 'Pull Request Acceptance Rate', 'experimental', '"pull-request-acceptance-rate"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:51:10', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (73, 'experimental', 'ghtorrent', 'metric', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/community_age', NULL, 'Community Age', 'experimental', '"community-age"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:51:11', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (74, 'experimental', 'ghtorrent', 'metric', 'implemented', 'unimplemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/contributions', NULL, 'Contributions', 'experimental', '"contributions"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:51:13', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (75, 'experimental', 'ghtorrent', 'metric', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/project_age', NULL, 'Project Age', 'experimental', '"project-age"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:51:14', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (76, 'experimental', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/fakes', NULL, 'Fakes', 'experimental', '"fakes"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:51:16', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (77, 'experimental', 'ghtorrent', 'timeseries', 'implemented', 'unimplemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/total_watchers', NULL, 'Total Watchers', 'experimental', '"total-watchers"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:51:18', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (78, 'experimental', 'ghtorrent', 'timeseries', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/timeseries/new_watchers', NULL, 'New Watchers', 'experimental', '"new-watchers"', 'Insight Worker', '0.0.1', 'ghtorrent', '2019-06-20 22:51:19', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (79, 'experimental', 'librariesio', 'metric', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/dependencies', NULL, 'Dependencies', 'experimental', '"dependencies"', 'Insight Worker', '0.0.1', 'librariesio', '2019-06-20 22:51:21', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (80, 'experimental', 'librariesio', 'metric', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/dependency_stats', NULL, 'Dependency Stats', 'experimental', '"dependency-stats"', 'Insight Worker', '0.0.1', 'librariesio', '2019-06-20 22:51:23', NULL);
INSERT INTO "augur_data"."chaoss_metric_status" VALUES (81, 'experimental', 'librariesio', 'metric', 'implemented', 'implemented', 'f', '/api/unstable/<owner>/<repo>/dependents', NULL, 'Dependents', 'experimental', '"dependents"', 'Insight Worker', '0.0.1', 'librariesio', '2019-06-20 22:51:25', NULL);
COMMIT;

BEGIN;
INSERT INTO "augur_data"."contributor_affiliations"("cntrb_id", "ca_id", "ca_domain", "ca_affiliation", "ca_start_date", "ca_active", "ca_last_modified", "tool_source", "tool_version", "data_source", "data_collection_date") VALUES (1, 25152, 'goggins.com', 'goggins', '2016-03-03', 1, '2019-10-29 12:22:25', NULL, NULL, NULL, '2019-10-29 17:22:30');
COMMIT; 

