name: Build Docker images
on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master
  release:
    types: 
      - published

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
      - name: Run the build
        run: |
          # use that here since the variable are not present before start, so can't be in env
          export LOGIN=$GITHUB_REPOSITORY_OWNER

          echo $PASSWORD | docker login $REGISTRY -u $LOGIN --password-stdin

          for i in utils/docker/*; do
            export IMAGE=$LOGIN/augur_$(dirname $i)
            DOCKERFILE=${i}/Dockerfile
            TAG=todo
            docker build . -f $DOCKERFILE --tag $REGISTRY/$IMAGE:$TAG --tag $REGISTRY/$IMAGE:latest
            echo "$GITHUB_EVENT_NAME"
            if $GITHUB_EVENT_NAME -eq 'release'; then
              docker push $REGISTRY/$IMAGE:latest
              docker push $REGISTRY/$IMAGE:$TAG
            fi
          done
        env:
          REGISTRY: ghcr.io
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}

