name: Welcome

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for opening an issue! Please make sure you''ve included all relevant debugging information and we''ll help you as soon as we can!'
        pr-message: 'Thanks for opening a PR! Please make sure you''ve included all relevant documentation changes and have clearly explained the purpose of your patch and we''ll help you as soon as we can!'
